/*
 * File: app/view/LogInFrm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMightMobile.view.LogInFrm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Radio',
        'Ext.field.Password',
        'Ext.Button'
    ],

    config: {
        height: '100%',
        itemId: 'registrationLoginFrm1',
        padding: '200 200 200 200',
        scrollable: false,
        submitOnAction: false,
        items: [
            {
                xtype: 'fieldset',
                hidden: true,
                title: '',
                items: [
                    {
                        xtype: 'radiofield',
                        itemId: 'myradiobutton4',
                        label: 'Login',
                        name: 'loginType',
                        value: 'loginChk',
                        checked: true
                    },
                    {
                        xtype: 'radiofield',
                        label: 'New Boat',
                        name: 'loginType',
                        value: 'newChk'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                itemId: 'seriesDetails',
                title: 'Login',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'lUsername',
                        label: 'Username / Crew Member',
                        labelWidth: '40%',
                        name: 'username',
                        required: true
                    },
                    {
                        xtype: 'passwordfield',
                        itemId: 'lPassword',
                        label: 'Password',
                        labelWidth: '40%',
                        name: 'password'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 40,
                itemId: 'bottomCt',
                items: [
                    {
                        xtype: 'button',
                        docked: 'right',
                        itemId: 'lLoginBtn',
                        ui: 'decline-round',
                        text: 'Login'
                    },
                    {
                        xtype: 'button',
                        docked: 'left',
                        hidden: true,
                        itemId: 'backLoginBtn1',
                        ui: 'decline-round',
                        text: '<< Back'
                    }
                ]
            }
        ]
    }

});