/*
 * File: app/view/MenuView.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMightMobile.view.MenuView', {
    extend: 'Ext.Container',

    requires: [
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.util.DelayedTask'
    ],

    config: {
        cls: 'a',
        itemId: 'mycontainer55',
        layout: 'fit',
        items: [
            {
                xtype: 'dataview',
                itemId: 'menuView',
                margin: '70 130 0 130',
                inline: true,
                itemTpl: [
                    '{[GetTemplate(\'menu\', values)]}'
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMenuViewSelect',
                event: 'select',
                delegate: '#menuView'
            }
        ]
    },

    onMenuViewSelect: function(dataview, record, eOpts) {

        var me = DynaMightMobile.app.getController('Navigation'),
            item = record.data,
            className = item.name.replace(/ /g, '');

        Ext.Viewport.setMasked(true);
        //me.getHomePanel().removeAll(false,false);
        //me.applyClass(item.name.replace(/ /g, ''));
        new Ext.util.DelayedTask(function(){

            if(item.entityid){
                me.applyList(item);
            }
            else {
                me.applyClass(item.name.replace(/ /g, ''));
            }

            me.getTopCardLbl().setHtml('Canberra Yacht Club - ' + item.name);
        }).delay(250);

    },

    initialize: function() {
        this.callParent();

        Ext.Viewport.setMasked(false);
    }

});