/*
 * File: app/view/ResultsEditor.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMightMobile.view.ResultsEditor', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Button',
        'Ext.field.Search',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Toolbar',
        'Ext.Spacer',
        'Ext.ux.picker.Time',
        'Ext.ux.field.TimePicker',
        'Ext.data.JsonP'
    ],

    config: {
        itemId: 'receResultEdit',
        layout: 'card',
        scrollable: false,
        items: [
            {
                xtype: 'formpanel',
                itemId: 'editSeriesPnl',
                layout: 'hbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'fieldset',
                        flex: 1,
                        margin: 5,
                        layout: 'fit',
                        title: 'Select a Series',
                        items: [
                            {
                                xtype: 'list',
                                itemId: 'seriesEditorList',
                                itemTpl: Ext.create('Ext.XTemplate', 
                                    '<div class="icon-wrapper">',
                                    '    <div class="icon" style={[this.getPath(values.path)]}>',
                                    '    </div>',
                                    '</div>',
                                    '<div class="item">',
                                    '    <table><tr>',
                                    '        <td>',
                                    '            <div class="name">{name}</div>',
                                    '            <div class="vicinity">{[this.DateFormat(values.earlieststarttime)]}</div>',
                                    '            <div class="vicinity">{entrycost}</div>',
                                    '            <div class="vicinity">{type}</div>',
                                    '        </td>',
                                    '        <td style="padding-left: 30px;display: block;padding-top: 5px;">',
                                    '            <div class="vicinity">{description}</div>',
                                    '        </td>',
                                    '        </tr>',
                                    '    </table>',
                                    '    ',
                                    '</div>',
                                    {
                                        getPath: function(path) {
                                            //debugger;
                                            return "background-size:50px;background-image:url('" + RES_URL + "admin/uploaded_files/" + path + "')";
                                        },
                                        DateFormat: function(date) {
                                            //debugger;
                                            return Ext.Date.format(new Date(date), 'Y-m-d H:i');
                                        }
                                    }
                                )
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 1,
                        itemId: 'racesCt',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                margin: 5,
                                layout: 'fit',
                                title: 'Races',
                                items: [
                                    {
                                        xtype: 'list',
                                        itemId: 'racesEditorList',
                                        itemTpl: Ext.create('Ext.XTemplate', 
                                            '',
                                            '<div class="item">',
                                            '    <div class="name">{name}',
                                            '    </div>',
                                            '    <div class="vicinity">Start time: {[this.DateFormat(values.startdate)]}',
                                            '    </div>',
                                            '    ',
                                            '</div>',
                                            {
                                                DateFormat: function(date) {
                                                    return Ext.Date.format(date, 'Y-m-d H:i');
                                                }
                                            }
                                        )
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                itemId: 'buttonsCt'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 1,
                        docked: 'top',
                        height: 40,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'editRaceBtn',
                                ui: 'decline-round',
                                text: 'Edit Race'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'editorFrm',
                layout: 'fit',
                scrollable: false,
                items: [
                    {
                        xtype: 'fieldset',
                        itemId: 'boatRacesAssignCrewFS',
                        margin: 5,
                        layout: 'vbox',
                        title: 'Boat',
                        items: [
                            {
                                xtype: 'dataview',
                                flex: 1,
                                itemId: 'resultBoatsView',
                                inline: true,
                                itemTpl: [
                                    '{[GetTemplate(\'boatresult\', values)]}',
                                    ''
                                ]
                            },
                            {
                                xtype: 'container',
                                docked: 'top',
                                itemId: 'hControlls1',
                                margin: 10,
                                defaults: {
                                    margin: '5'
                                },
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        itemId: 'editResDivisionCmb',
                                        label: 'Division',
                                        displayField: 'name',
                                        valueField: 'divisionid'
                                    },
                                    {
                                        xtype: 'searchfield',
                                        itemId: 'editResBoatSearch',
                                        width: 231,
                                        label: 'Boat'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                itemId: 'botButtonsCt1',
                                margin: 10,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        itemId: 'resEditCt',
                                        layout: {
                                            type: 'hbox',
                                            align: 'start'
                                        },
                                        items: [
                                            {
                                                xtype: 'button',
                                                height: 35,
                                                hidden: true,
                                                itemId: 'adjustTimeBtn',
                                                margin: 10,
                                                ui: 'decline-round',
                                                width: 241,
                                                text: 'Adjust Time'
                                            },
                                            {
                                                xtype: 'selectfield',
                                                itemId: 'editBoatStatusCmb',
                                                label: 'Status',
                                                displayField: 'code',
                                                valueField: 'boatstatusid'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                itemId: 'botButtonsCt2',
                                margin: 10,
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        itemId: 'resEditCt2',
                                        layout: {
                                            type: 'hbox',
                                            align: 'start'
                                        },
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                itemId: 'handicapTxt',
                                                label: 'Handicap'
                                            },
                                            {
                                                xtype: 'datepickerfield',
                                                itemId: 'resEditDatePicker',
                                                label: 'Date',
                                                placeHolder: '',
                                                picker: {
                                                    yearFrom: 2014
                                                }
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'button',
                                        disabled: false,
                                        docked: 'right',
                                        itemId: 'resEditorApplyBtn',
                                        margin: '0 20 0 20',
                                        ui: 'confirm-round',
                                        text: 'Calculate Results'
                                    },
                                    {
                                        xtype: 'button',
                                        disabled: false,
                                        itemId: 'resEditorApplyBtn1',
                                        margin: '0 20 0 20',
                                        ui: 'action-round',
                                        text: 'Apply'
                                    },
                                    {
                                        xtype: 'button',
                                        disabled: false,
                                        itemId: 'resEditorAddBtn',
                                        margin: '0 20 0 20',
                                        ui: 'action-round',
                                        text: 'Add Boat'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        hidden: true,
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                itemId: 'setCrewToRaceBoat',
                                ui: 'confirm',
                                width: 150,
                                text: 'Save Result'
                            }
                        ]
                    }
                ],
                listeners: [
                    {
                        fn: function(component, eOpts) {

                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'formpanel',
                height: '100%',
                itemId: 'selectBoat',
                layout: 'vbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'fieldset',
                        flex: 1,
                        layout: 'vbox',
                        title: 'Select Boat',
                        items: [
                            {
                                xtype: 'selectfield',
                                itemId: 'reviewDivisionCmb',
                                maxWidth: 400,
                                label: 'Division',
                                displayField: 'name',
                                valueField: 'divisionid'
                            },
                            {
                                xtype: 'dataview',
                                flex: 1,
                                itemId: 'editAddBoatsList',
                                inline: true,
                                itemTpl: [
                                    '{[GetTemplate(\'boatadd\', values)]}'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 40,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'left',
                                hidden: false,
                                itemId: 'CancelSelectBtn',
                                ui: 'decline-round',
                                text: 'Cancel'
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'confirmSelectedBoats',
                                ui: 'confirm-round',
                                text: 'Select'
                            }
                        ]
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();

        var me = this,
            dStore = CreateStore("division"),
            rsStore = CreateStore("boatstatus"),
            ctrl = DynaMightMobile.app.getController('RaceResults'),
            raceSeriesStore = CreateStore("raceseries"),
            raceStore = CreateStore("race");


        raceStore.filter('raceseriesid', '1');



        dStore.execConfig({
            params: {
                entityViewID: GetEntityViewByName('AllDivisions').entityviewid ,
                filters: ''
            }
        });
        //return;


        rsStore.execConfig({
            params: {
                entityViewID: GetEntityViewByName('Boat Status').entityviewid ,
                filters: ''
            }
        });

        raceSeriesStore.execConfig({
            params: {
                entityViewID: GetEntityViewByName('Race Series').entityviewid ,
                filters: ''
            }
        });

        raceStore.execConfig({
            params: {
                entityViewID: GetEntityViewByName('Races').entityviewid ,
                filters: 'WHERE startdate < now() order by startdate desc'
            }
        });



        me.down('#editResDivisionCmb').setStore(dStore);

        me.down('#editBoatStatusCmb').setStore(rsStore);

        me.down('#seriesEditorList').setStore(raceSeriesStore);
        me.down('#racesEditorList').setStore(raceStore);


        me.down('#resEditCt').add({
            xtype: 'timepickerfield',
            itemId: 'editBoatTime',
            name: 'defaultTime',
            label: 'Time',
            dateFormat: 'H:i:s',
            picker:{

                slotOrder: ['hour','minute','second'],
                endHour: 23
            },
            listeners: {
                hide: me.onBoatTimeChange
            }
        });


        Ext.Viewport.setMasked(false);
    },

    onBoatTimeChange: function(a, b, c) {
        //debugger;
    }

});