/*
 * File: app/view/RFReview.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMightMobile.view.RFReview', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.FieldSet',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.Button',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.ux.picker.Time',
        'Ext.ux.field.TimePicker'
    ],

    config: {
        height: '100%',
        itemId: 'rfReviewFrm',
        layout: 'vbox',
        scrollable: false,
        items: [
            {
                xtype: 'fieldset',
                flex: 1,
                layout: 'vbox',
                title: 'Competitor Information',
                items: [
                    {
                        xtype: 'selectfield',
                        itemId: 'reviewDivisionCmb',
                        maxWidth: 400,
                        label: 'Division',
                        displayField: 'name',
                        valueField: 'divisionid'
                    },
                    {
                        xtype: 'dataview',
                        flex: 1,
                        itemId: 'raceBoatsReviewList',
                        inline: true,
                        itemTpl: Ext.create('Ext.XTemplate', 
                            '{[GetTemplate(\'boattime\', values)]}',
                            {
                                getTime: function(date) {
                                    return date.split(' ')[1];
                                }
                            }
                        )
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'botButtonsCt',
                margin: 10,
                layout: 'hbox',
                items: [
                    {
                        xtype: 'container',
                        itemId: 'editCt',
                        layout: {
                            type: 'hbox',
                            align: 'start'
                        },
                        items: [
                            {
                                xtype: 'button',
                                height: 35,
                                hidden: true,
                                itemId: 'adjustTimeBtn',
                                margin: 10,
                                ui: 'decline-round',
                                width: 241,
                                text: 'Adjust Time'
                            },
                            {
                                xtype: 'selectfield',
                                itemId: 'raceStatusCmb',
                                label: 'Status',
                                displayField: 'code',
                                valueField: 'boatstatusid'
                            },
                            {
                                xtype: 'datepickerfield',
                                docked: 'right',
                                itemId: 'datePicker',
                                label: 'Date',
                                placeHolder: '',
                                picker: {
                                    itemId: 'mydatepicker9'
                                }
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        disabled: true,
                        itemId: 'reviewApplyBtn',
                        margin: '0 20 0 20',
                        ui: 'action-round',
                        text: 'Apply'
                    }
                ]
            },
            {
                xtype: 'container',
                docked: 'bottom',
                height: 40,
                itemId: 'bottomCt',
                margin: 10,
                items: [
                    {
                        xtype: 'button',
                        docked: 'left',
                        hidden: true,
                        itemId: 'backResultsBtn',
                        ui: 'decline-round',
                        text: 'Back'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        itemId: 'finalizeResultsBtn',
                        ui: 'confirm-round',
                        text: 'Finalise Results'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();

        var me = this,
            rsStore = CreateStore("boatstatus"),
            ctrl = DynaMightMobile.app.getController('RaceFinishWizard');

        rsStore.execConfig({
            params: {
                entityViewID: GetEntityViewByName('Boat Status').entityviewid ,
                filters: ''
            }
        });

        me.down('#editCt').add({
            xtype: 'timepickerfield',
            itemId: 'boatTime',
            name: 'defaultTime',
            label: 'Time',
            dateFormat: 'H:i:s',
            picker:{

                slotOrder: ['hour','minute','second'],
                endHour: 23
            },
            listeners: {
                hide: me.onBoatTimeChange
            }
        });


        me.down('#raceBoatsReviewList').setStore(ctrl.finishView);
        me.down('#raceStatusCmb').setStore(rsStore);
        me.down('#reviewDivisionCmb').setStore(ctrl.dStore);

        ctrl.raceBoats = me.down('#raceBoatsReviewList');
    },

    onBoatTimeChange: function(a, b, c) {
        //debugger;
    }

});