/*
 * File: app/view/SeriesWizard.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMightMobile.view.SeriesWizard', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.field.TextArea',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.field.File',
        'Ext.field.Radio',
        'Ext.field.Spinner',
        'Ext.Label'
    ],

    config: {
        itemId: 'seriesWizardId',
        scrollable: false,
        layout: {
            type: 'card',
            animation: 'slide'
        },
        items: [
            {
                xtype: 'formpanel',
                cls: 'wizard',
                itemId: 'seriesDetailsFrm',
                scrollable: false,
                items: [
                    {
                        xtype: 'selectfield',
                        hidden: true,
                        itemId: 'yachtClubCmb',
                        width: 875,
                        label: 'Yacht club',
                        name: 'raceseriesyachtclubid',
                        displayField: 'name',
                        valueField: 'yachtclubid'
                    },
                    {
                        xtype: 'fieldset',
                        cls: 'wizard',
                        itemId: 'seriesDetails',
                        margin: 5,
                        title: 'Series Details',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'SeriesName',
                                label: 'Name',
                                name: 'name',
                                required: true
                            },
                            {
                                xtype: 'textfield',
                                label: 'Location',
                                name: 'location'
                            },
                            {
                                xtype: 'numberfield',
                                label: 'Entry Cost',
                                name: 'entrycost'
                            },
                            {
                                xtype: 'numberfield',
                                label: 'Race Cost',
                                name: 'raceentrycost'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Key Contact',
                                name: 'keycontact'
                            },
                            {
                                xtype: 'datepickerfield',
                                itemId: 'earlieststarttime',
                                label: 'Start',
                                name: 'earlieststarttime',
                                placeHolder: 'mm/dd/yyyy',
                                usePicker: false
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        itemId: 'sponsorDetails',
                        margin: 5,
                        title: 'Sponsor',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Name',
                                name: 'sponsorname'
                            },
                            {
                                xtype: 'textfield',
                                hidden: true,
                                label: 'Logo',
                                name: 'logo'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Link',
                                name: 'link'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 35,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'nextBtn',
                                ui: 'decline-round',
                                text: 'Next  >>'
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                hidden: true,
                                itemId: 'backBtn',
                                text: '<< Back'
                            }
                        ]
                    }
                ],
                listeners: [
                    {
                        fn: function(element, eOpts) {
                            //alert('y');
                            Ext.Viewport.setMasked(false);

                        },
                        event: 'painted'
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'seriesOptionsFrm',
                scrollable: false,
                items: [
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 35,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'nextBtn',
                                ui: 'decline-round',
                                text: 'Next  >>'
                            },
                            {
                                xtype: 'button',
                                docked: 'right',
                                hidden: true,
                                itemId: 'backBtn',
                                text: '<< Back'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Series Options',
                        items: [
                            {
                                xtype: 'selectfield',
                                itemId: 'seriesSelect',
                                label: 'Import Messages from Series',
                                displayField: 'name'
                            },
                            {
                                xtype: 'checkboxfield',
                                itemId: 'signOnChk',
                                label: 'Sign On ',
                                name: 'signoncheck'
                            },
                            {
                                xtype: 'checkboxfield',
                                hidden: true,
                                itemId: 'mobileSignOnChk',
                                label: 'Allow Mobile App Sign On',
                                name: 'mobilesignoncheck'
                            },
                            {
                                xtype: 'textareafield',
                                hidden: true,
                                itemId: 'signOnMessageTxt',
                                label: 'Sign On Message',
                                name: 'signonmessage'
                            },
                            {
                                xtype: 'checkboxfield',
                                itemId: 'signOffChk',
                                label: 'Sign Off',
                                name: 'signoffcheck'
                            },
                            {
                                xtype: 'checkboxfield',
                                hidden: true,
                                itemId: 'mobileSignOffChk',
                                label: 'Allow Mobile App Sign Off',
                                name: 'mobilesignoffcheck'
                            },
                            {
                                xtype: 'textareafield',
                                hidden: true,
                                itemId: 'signOffMessageTxt',
                                label: 'Sign Off Message',
                                name: 'signoffmessage'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'divisionDetails',
                layout: 'vbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'container',
                        flex: 5,
                        itemId: 'divisionCt',
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                layout: 'fit',
                                title: 'Divisions',
                                items: [
                                    {
                                        xtype: 'list',
                                        itemId: 'raceDivisionsList',
                                        itemTpl: Ext.create('Ext.XTemplate', 
                                            '',
                                            '',
                                            '<div class="icon-wrapper">',
                                            '    <div class="icon" style={[this.getPath(values.path)]}>',
                                            '    </div>',
                                            '</div>',
                                            '<div class="item">',
                                            '    <div class="name">',
                                            '        {name}',
                                            '        <tpl if="values.groupname">',
                                            '            <span style = "margin-right:5px;">({groupname})</span>',
                                            '        </tpl>',
                                            '        ',
                                            '        <tpl if="values.handicaptype">',
                                            '         <span style = "margin-right:5px;"> - {handicaptype}</span>',
                                            '        </tpl>',
                                            '    </div>',
                                            '    <div class="vicinity">',
                                            '    </div>',
                                            '    ',
                                            '    <div class="name">{description}',
                                            '    </div>',
                                            '    ',
                                            '    ',
                                            '</div>',
                                            {
                                                getPath: function(path) {
                                                    //debugger;
                                                    return "background-size:cover;background-image:url('../admin/uploaded_files/"+ path +"')";
                                                }
                                            }
                                        )
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                itemId: 'divisionButtonsCt',
                                defaults: {
                                    margin: '5 0 0 0'
                                },
                                layout: {
                                    type: 'vbox',
                                    pack: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'addDivisionBtn',
                                        ui: 'action-round',
                                        text: '< Add'
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'allDivisionsBtn',
                                        ui: 'action-round',
                                        text: '<< All'
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'delDivisionBtn',
                                        ui: 'action-round',
                                        text: 'Rem >'
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'newDivisionBtn',
                                        ui: 'action-round',
                                        text: 'New'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                layout: 'fit',
                                title: 'Previously Used Divisions',
                                items: [
                                    {
                                        xtype: 'list',
                                        itemId: 'divisionsList',
                                        itemTpl: Ext.create('Ext.XTemplate', 
                                            '',
                                            '',
                                            '<div class="icon-wrapper">',
                                            '    <div class="icon" style={[this.getPath(values.path)]}>',
                                            '    </div>',
                                            '</div>',
                                            '<div class="item">',
                                            '    <div class="name">',
                                            '        {name}',
                                            '        <tpl if="values.groupname">',
                                            '            <span style = "margin-right:5px;">({groupname})</span>',
                                            '        </tpl>',
                                            '        ',
                                            '        <tpl if="values.handicaptype">',
                                            '         <span style = "margin-right:5px;"> - {handicaptype}</span>',
                                            '        </tpl>',
                                            '    </div>',
                                            '    <div class="vicinity">',
                                            '    </div>',
                                            '    ',
                                            '    <div class="name">{description}',
                                            '    </div>',
                                            '    ',
                                            '    ',
                                            '</div>',
                                            {
                                                getPath: function(path) {
                                                    return "background-size:cover;background-image:url('../admin/uploaded_files/"+ path +"')";
                                                }
                                            }
                                        ),
                                        itemHeight: 24
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 1,
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                flex: 1,
                                height: 30,
                                hidden: true,
                                itemId: 'addNewDivisionBtn',
                                ui: 'action-round',
                                text: 'New devision'
                            },
                            {
                                xtype: 'button',
                                flex: 1,
                                height: 30,
                                itemId: 'updateDivisionBtn',
                                ui: 'action-round',
                                text: 'Edit division'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 40,
                        itemId: 'bottomCt1',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                hidden: false,
                                itemId: 'nextBtn',
                                ui: 'decline-round',
                                text: 'Next >>'
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                itemId: 'backBtn',
                                ui: 'decline-round',
                                text: '<< Back'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'divisionDetailsEdit',
                scrollable: false,
                items: [
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'fieldset',
                                width: 541,
                                title: 'Division Details',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        label: 'Name',
                                        name: 'name'
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: 'Group',
                                        name: 'group'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        itemId: 'handicapTypeTxt',
                                        label: 'Handicap Type',
                                        name: 'handicaptype',
                                        autoSelect: false,
                                        hiddenName: 'handicaptype',
                                        options: [
                                            {
                                                text: 'CBH',
                                                value: 'CBH'
                                            },
                                            {
                                                text: 'YS',
                                                value: 'YS'
                                            },
                                            {
                                                text: 'TCF',
                                                value: 'TCF'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'textfield',
                                        hidden: true,
                                        itemId: 'handicapValueTxt',
                                        label: 'Handicap Value',
                                        name: 'handicapvalue'
                                    },
                                    {
                                        xtype: 'textareafield',
                                        label: 'Description',
                                        name: 'description'
                                    },
                                    {
                                        xtype: 'filefield',
                                        hidden: true,
                                        label: 'Flag',
                                        name: 'flag'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        flex: 1,
                                        height: 30,
                                        itemId: 'saveDivisionBtn',
                                        margin: '110 0 0 20',
                                        maxWidth: 200,
                                        minWidth: 200,
                                        ui: 'action-round',
                                        width: 200,
                                        text: 'OK'
                                    },
                                    {
                                        xtype: 'button',
                                        flex: 1,
                                        height: 30,
                                        itemId: 'cancelDivisionBtn',
                                        margin: '110 0 0 20',
                                        maxWidth: 200,
                                        minWidth: 200,
                                        ui: 'action-round',
                                        width: 200,
                                        text: 'Cancel'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 40,
                        itemId: 'bottomCt1',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                hidden: true,
                                itemId: 'nextBtn',
                                ui: 'decline-round',
                                text: 'Next >>'
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                itemId: 'backBtn',
                                ui: 'decline-round',
                                text: '<< Back'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'raceDetails',
                scrollable: false,
                items: [
                    {
                        xtype: 'container',
                        height: 410,
                        layout: {
                            type: 'hbox',
                            align: 'start'
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                                docked: 'left',
                                margin: '0 0 5 10',
                                width: '90%',
                                layout: 'fit',
                                title: 'Race Details',
                                items: [
                                    {
                                        xtype: 'list',
                                        itemId: 'racesList',
                                        emptyText: 'Races',
                                        itemTpl: Ext.create('Ext.XTemplate', 
                                            '',
                                            '<div class="item">',
                                            '    <div class="name">{name}',
                                            '    </div>',
                                            '    <div class="vicinity">Start time: {[this.DateFormat(values.startdate)]}',
                                            '    </div>',
                                            '    ',
                                            '</div>',
                                            {
                                                DateFormat: function(date) {
                                                    return Ext.Date.format(date, 'Y-m-d H:i');
                                                }
                                            }
                                        ),
                                        itemHeight: 50
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                docked: 'left',
                                defaults: {
                                    margin: '5 0 0 0'
                                },
                                layout: {
                                    type: 'vbox',
                                    pack: 'center'
                                },
                                items: [
                                    {
                                        xtype: 'button',
                                        itemId: 'addNewRace',
                                        ui: 'action-round',
                                        text: 'Add'
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'delBtn',
                                        ui: 'action-round',
                                        text: 'Rem'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        cls: 'raceZone',
                        itemId: 'bottomCtId',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'container',
                                itemId: 'raceCt1',
                                width: 438,
                                items: [
                                    {
                                        xtype: 'textfield',
                                        hidden: true,
                                        itemId: 'sponsorNameTxt',
                                        label: 'Name',
                                        name: 'sponsorname'
                                    },
                                    {
                                        xtype: 'textfield',
                                        hidden: true,
                                        label: 'Logo',
                                        name: 'sponsorlogo'
                                    },
                                    {
                                        xtype: 'textfield',
                                        hidden: true,
                                        itemId: 'linkTxt',
                                        label: 'Link',
                                        name: 'sponsorlink'
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'updateRaceBtn',
                                        ui: 'action-round',
                                        width: 200,
                                        text: 'Edit race'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 40,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'nextBtn',
                                ui: 'decline-round',
                                text: 'Next >>'
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                itemId: 'backBtn',
                                ui: 'decline-round',
                                text: '<< Back'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'raceDetailsEdit',
                scrollable: false,
                items: [
                    {
                        xtype: 'container',
                        cls: 'raceZone',
                        itemId: 'bottomCtId',
                        items: [
                            {
                                xtype: 'fieldset',
                                itemId: 'raceCtId',
                                width: 438,
                                title: 'Race details',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        itemId: 'nameTxt',
                                        label: 'Name',
                                        name: 'name',
                                        required: true
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        itemId: 'startdateId',
                                        label: 'Date',
                                        value: {
                                            year: 2014,
                                            month: 9,
                                            day: 10
                                        },
                                        placeHolder: 'dd/mm/yyyy',
                                        dateFormat: 'd/m/Y'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        flex: 1,
                                        itemId: 'saveRaceBtn',
                                        maxWidth: 200,
                                        minWidth: 200,
                                        ui: 'action-round',
                                        width: 200,
                                        text: 'OK'
                                    },
                                    {
                                        xtype: 'button',
                                        flex: 1,
                                        itemId: 'cancelRaceEditBtn',
                                        maxWidth: 200,
                                        minWidth: 200,
                                        ui: 'action-round',
                                        width: 200,
                                        text: 'Cancel'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                itemId: 'raceCt1',
                                width: 438,
                                items: [
                                    {
                                        xtype: 'textfield',
                                        hidden: true,
                                        itemId: 'sponsorNameTxt',
                                        label: 'Name',
                                        name: 'sponsorname'
                                    },
                                    {
                                        xtype: 'textfield',
                                        hidden: true,
                                        label: 'Logo',
                                        name: 'sponsorlogo'
                                    },
                                    {
                                        xtype: 'textfield',
                                        hidden: true,
                                        itemId: 'linkTxt',
                                        label: 'Link',
                                        name: 'sponsorlink'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 40,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                hidden: true,
                                itemId: 'nextBtn',
                                ui: 'decline-round',
                                text: 'Next >>'
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                itemId: 'backBtn',
                                ui: 'decline-round',
                                text: '<< Back'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'raceAddFrm',
                scrollable: false,
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Blank Race(s)',
                        items: [
                            {
                                xtype: 'numberfield',
                                itemId: 'newTxt',
                                labelWidth: 0,
                                value: 1,
                                minValue: 1
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        height: 410,
                        items: [
                            {
                                xtype: 'fieldset',
                                docked: 'left',
                                height: '100%',
                                width: 550,
                                layout: 'vbox',
                                title: 'Patter of Races',
                                items: [
                                    {
                                        xtype: 'formpanel',
                                        cls: 'generateStart',
                                        height: 65,
                                        itemId: 'startFrm',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'datepickerfield',
                                                itemId: 'defaultStartDt',
                                                margin: 10,
                                                width: 304,
                                                label: 'Start Date',
                                                labelWidth: '50%',
                                                name: 'startdate',
                                                value: {
                                                    year: new Date().getFullYear(),
                                                    month: new Date().getMonth(),
                                                    day: new Date().getDate()
                                                },
                                                placeHolder: 'dd/mm/yyyy',
                                                dateFormat: 'd/m/Y',
                                                picker: {
                                                    slotOrder: [
                                                        'day',
                                                        'month',
                                                        'year'
                                                    ],
                                                    yearTo: 2016
                                                }
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'formpanel',
                                        flex: 1,
                                        cls: 'generateZone',
                                        itemId: 'patternFrm',
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                margin: '10 10 10 10',
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'radiofield',
                                                        margin: '0 5 0 0',
                                                        width: 200,
                                                        label: 'End after:',
                                                        labelAlign: 'right',
                                                        labelWidth: '50%',
                                                        name: 'endRadio',
                                                        value: 'endAfterRadio',
                                                        checked: true
                                                    },
                                                    {
                                                        xtype: 'spinnerfield',
                                                        itemId: 'occurencesSpinner',
                                                        margin: '0 10 0 0',
                                                        width: 149,
                                                        labelAlign: 'right',
                                                        labelWidth: '50%',
                                                        name: 'occurences',
                                                        minValue: 1,
                                                        stepValue: 1
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        html: 'occurences',
                                                        margin: 10
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                margin: '10 10 10 10 ',
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'radiofield',
                                                        margin: '0 5 0 0',
                                                        width: 200,
                                                        label: 'End by:',
                                                        labelAlign: 'right',
                                                        labelWidth: '50%',
                                                        name: 'endRadio',
                                                        value: 'endByRadio'
                                                    },
                                                    {
                                                        xtype: 'datepickerfield',
                                                        name: 'enddate',
                                                        value: {
                                                            year: 2014,
                                                            month: 9,
                                                            day: 10
                                                        },
                                                        placeHolder: 'dd/mm/yyyy',
                                                        dateFormat: 'd/m/Y',
                                                        picker: {
                                                            slotOrder: [
                                                                'day',
                                                                'month',
                                                                'year'
                                                            ],
                                                            yearTo: 2016
                                                        }
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                margin: '10 10 10 10 ',
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'spinnerfield',
                                                        itemId: 'weeksSpinner',
                                                        width: 226,
                                                        label: 'every:',
                                                        name: 'weeks',
                                                        minValue: 1,
                                                        stepValue: 1
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        html: 'week(s) on:',
                                                        margin: 10
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                margin: '0 0 0 10',
                                                width: 530,
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'checkboxfield',
                                                        itemId: 'mo',
                                                        width: 120,
                                                        label: 'Mon',
                                                        labelWidth: '45%',
                                                        name: '1'
                                                    },
                                                    {
                                                        xtype: 'checkboxfield',
                                                        itemId: 'tu',
                                                        width: 120,
                                                        label: 'Tue',
                                                        labelWidth: '45%',
                                                        name: '2'
                                                    },
                                                    {
                                                        xtype: 'checkboxfield',
                                                        itemId: 'we',
                                                        width: 120,
                                                        label: 'Wen',
                                                        labelWidth: '45%',
                                                        name: '3'
                                                    },
                                                    {
                                                        xtype: 'checkboxfield',
                                                        itemId: 'th',
                                                        width: 120,
                                                        label: 'Thu',
                                                        labelWidth: '45%',
                                                        name: '4'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                margin: '5 5 0 10',
                                                width: 537,
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'checkboxfield',
                                                        itemId: 'fr',
                                                        width: 120,
                                                        label: 'Fri',
                                                        labelWidth: '45%',
                                                        name: '5'
                                                    },
                                                    {
                                                        xtype: 'checkboxfield',
                                                        itemId: 'sa',
                                                        width: 120,
                                                        label: 'Sat',
                                                        labelWidth: '45%',
                                                        name: '6'
                                                    },
                                                    {
                                                        xtype: 'checkboxfield',
                                                        itemId: 'su',
                                                        width: 120,
                                                        label: 'Sun',
                                                        labelWidth: '45%',
                                                        name: '7'
                                                    },
                                                    {
                                                        xtype: 'button',
                                                        docked: 'right',
                                                        itemId: 'addPatternBtn',
                                                        margin: '10 ',
                                                        ui: 'action-round',
                                                        text: 'Add pattern'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        margin: '10 0 0 0',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'addRaceInListBtn',
                                margin: '10 10 10 10',
                                ui: 'action-round',
                                width: 200,
                                text: 'Add'
                            },
                            {
                                xtype: 'button',
                                itemId: 'cancelAllRaceInListBtn',
                                margin: '10 10 10 10',
                                ui: 'action-round',
                                width: 200,
                                text: 'Cancel'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 40,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                hidden: true,
                                itemId: 'nextBtn',
                                ui: 'decline-round',
                                text: 'Next >>'
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                itemId: 'backBtn',
                                ui: 'decline-round',
                                text: '<< Back'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'reviewCard',
                layout: 'vbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'Series info',
                        items: [
                            {
                                xtype: 'label',
                                itemId: 'seriesReview'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 1,
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                layout: 'fit',
                                title: 'Race info',
                                items: [
                                    {
                                        xtype: 'list',
                                        height: '',
                                        itemId: 'racesReviewList',
                                        itemTpl: Ext.create('Ext.XTemplate', 
                                            '<div class="item">',
                                            '    <div class="name">{name}',
                                            '    </div>',
                                            '    <div class="vicinity">Start time: {[this.DateFormat(values.startdate)]}',
                                            '    </div>',
                                            '    ',
                                            '</div>',
                                            {
                                                DateFormat: function(date) {
                                                    return Ext.Date.format(date, 'Y-m-d H:i');
                                                }
                                            }
                                        )
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                layout: 'fit',
                                title: 'Division info',
                                items: [
                                    {
                                        xtype: 'list',
                                        itemId: 'raceDivisionsReviewList',
                                        itemTpl: [
                                            '<div class="icon-wrapper">',
                                            '    <div class="icon" style="-webkit-mask-image:url(http://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png);">',
                                            '    </div>',
                                            '</div>',
                                            '<div class="item">',
                                            '    <div class="name">{name}',
                                            '    </div>',
                                            '    <div class="vicinity">',
                                            '    </div>',
                                            '    ',
                                            '</div>'
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 40,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'finishBtn',
                                ui: 'confirm-round',
                                text: 'Finish'
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                hidden: false,
                                itemId: 'backBtn',
                                ui: 'decline-round',
                                text: '<< Back'
                            }
                        ]
                    }
                ]
            }
        ]
    },

    initialize: function() {

        var me = this,
            raceSeriesStore = CreateStore("raceseries"),
            seriesStore = CreateStore("raceseries"),
            raceStore = CreateStore("race"),
            yachtClubStore = CreateStore("yachtclub"),
            yachtEntity = GetEntityByName("yachtclub"),
            divisionStore = CreateStore("division"),
            raceDivisionsStore = CreateStore("division"),
            divisionEntity = GetEntityByName("division");

        this.callParent();



        seriesStore.execConfig({
            params: {
                entityViewID: GetEntityViewByName('Race Series').entityviewid,
                filters: ''
            }
        });


        yachtClubStore.execConfig({
            params: {
                entityViewID: GetEntityView(yachtEntity.entityid).entityviewid ,
                filters: ''
            }
        });

        divisionStore.execConfig({
            params: {
                entityViewID: GetEntityView(divisionEntity.entityid).entityviewid ,
                filters: ''
            }
        });
        raceDivisionsStore.execConfig({
            params: {
                entityViewID: GetEntityView(divisionEntity.entityid).entityviewid ,
                filters: ''
            }
        });

        //debugger;

        me.down('#yachtClubCmb').setStore(yachtClubStore);
        me.down('#racesList').setStore(raceStore);
        me.down('#racesReviewList').setStore(raceStore);
        me.down('#raceDivisionsReviewList').setStore(raceDivisionsStore);
        me.down('#raceDivisionsList').setStore(raceDivisionsStore);
        me.down('#divisionsList').setStore(divisionStore);
        me.down('#earlieststarttime').setValue(new Date());
        me.down('#seriesSelect').setStore(seriesStore);

        me.down('#seriesDetails').add({
            xtype: 'colorpickerfield',
            itemId: 'colorPickerId',
            name: 'color',
            label: 'Color',
            value: '003366',
            listeners:{
                painted:function(field){
                    var text ="<div style='background-color: #003366; width: 75%; height: 2em; margin: .25em auto; border: 3px solid #000;'>&nbsp;</div>";
                    field.down('div[class*="x-field-mask"]').dom.innerHTML = text;
                }
            }
        });

        me.down('#raceCtId').add({
            xtype: 'timepickerfield',
            itemId: 'timeTxt',
            name: 'time',
            label: 'Time',
            dateFormat: 'H:i',
            //useMeridiem: false,
            picker:{

                slotOrder: ['hour','minute'],
                endHour: 23
            }

        });

        me.down('#startFrm').add({
            xtype: 'timepickerfield',
            itemId: 'defaultTimeTxt',
            name: 'defaultTime',
            label: 'Time',
            dateFormat: 'H:i',
            margin: '10',
            value: new Date(1,1,1,13,0),
            //useMeridiem: false,
            picker:{

                slotOrder: ['hour','minute'],
                endHour: 23
            }

        });


        raceSeriesStore.insert(0, {Name: 'New Series'});

        Ext.Viewport.setMasked(false);
    }

});