/*
 * File: app/view/SW.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMightMobile.view.SW', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.field.Number',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button'
    ],

    config: {
        itemId: 'swId',
        scrollable: false,
        layout: {
            type: 'card',
            animation: 'slide'
        },
        items: [
            {
                xtype: 'formpanel',
                cls: 'wizard',
                itemId: 'seriesDetailsFrm',
                scrollable: false,
                items: [
                    {
                        xtype: 'fieldset',
                        cls: 'wizard',
                        itemId: 'seriesDetails',
                        margin: 5,
                        title: 'Series Details',
                        items: [
                            {
                                xtype: 'textfield',
                                itemId: 'SeriesName',
                                label: 'Name',
                                name: 'name',
                                required: true
                            },
                            {
                                xtype: 'textfield',
                                label: 'Location',
                                name: 'location'
                            },
                            {
                                xtype: 'numberfield',
                                label: 'Entry Cost',
                                name: 'entrycost'
                            },
                            {
                                xtype: 'numberfield',
                                label: 'Race Cost',
                                name: 'raceentrycost'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Key Contact',
                                name: 'keycontact'
                            },
                            {
                                xtype: 'datepickerfield',
                                label: 'Start',
                                name: 'earlieststarttime',
                                value: {
                                    year: 2014,
                                    month: 9,
                                    day: 22
                                },
                                placeHolder: 'mm/dd/yyyy',
                                usePicker: false
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        itemId: 'sponsorDetails',
                        margin: 5,
                        title: 'Sponsor',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Name',
                                name: 'sponsorname'
                            },
                            {
                                xtype: 'textfield',
                                hidden: true,
                                label: 'Logo',
                                name: 'logo'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Link',
                                name: 'link'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 35,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'swNextBtn',
                                ui: 'decline-round',
                                text: 'Next  >>'
                            }
                        ]
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();

        Ext.Viewport.setMasked(false);

        //APPSW = new DynaMightMobile.view.SeriesWizard();
    }

});