/*
 * File: app/view/ClubCalendar.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMight.view.ClubCalendar', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.calendar.util.Date',
        'Ext.calendar.CalendarPanel',
        'Ext.calendar.data.MemoryCalendarStore',
        'Ext.calendar.data.MemoryEventStore',
        'Ext.calendar.data.Events',
        'Ext.calendar.data.Calendars',
        'Ext.calendar.form.EventWindow'
    ],

    layout: 'fit',
    title: 'Club Calendar',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        me.processEventTypesCmb({
                            xtype: 'combobox',
                            itemId: 'eventTypesCmb',
                            fieldLabel: 'Event types',
                            value: 0,
                            editable: false,
                            displayField: 'name',
                            valueField: 'eventtypeid',
                            listeners: {
                                select: {
                                    fn: me.onEventTypesCmbSelect,
                                    scope: me
                                }
                            }
                        }),
                        me.processSeriesCmb({
                            xtype: 'combobox',
                            itemId: 'seriesCmb',
                            fieldLabel: 'Race series',
                            value: 0,
                            editable: false,
                            displayField: 'name',
                            valueField: 'raceseriesid',
                            listeners: {
                                select: {
                                    fn: me.onSeriesCmbSelect,
                                    scope: me
                                }
                            }
                        })
                    ]
                }
            ]
        });

        me.processClubCalendar(me);
        me.callParent(arguments);
    },

    processClubCalendar: function(config) {
        var me = this,
            calendarStore,
            raceStore = new Ext.data.Store({model: 'race'}),
            entityView = GetEntityViewByViewName('Club Calendar');

        //debugger;
        raceStore.execConfig({
            params: {
                entityViewID: entityView.entityviewid,
                filter: config.filters
            },
            callback: function(store){

                calendarStore = Ext.create('Ext.calendar.data.MemoryEventStore', {
                    data: me.processRaceData(store.data)
                });


                me.onCalendar(calendarStore);
            }
        });
    },

    processEventTypesCmb: function(config) {
        var typesStore = new Ext.data.Store({model: 'eventtype'}),
            typesView = GetEntityViewByName('eventtype');

        //debugger;
        typesStore.execConfig({
            params: {entityViewID: typesView.entityviewid},
            callback: function(store){
                store.insert(0,{
                    name: 'All',
                    eventtypeid: 0
                });
                store.insert(1,{
                    name: '(None)',
                    eventtypeid: -1
                });
            }
        });
        config.store = typesStore;
        return config;
    },

    processSeriesCmb: function(config) {
        var typesStore = new Ext.data.Store({model: 'raceseries'}),
            typesView = GetEntityViewByName('raceseries');

        //debugger;
        typesStore.execConfig({
            params: {entityViewID: typesView.entityviewid},
            callback: function(store){
                store.insert(0,{
                    name: 'All',
                    raceseriesid: 0
                });
                store.insert(1,{
                    name: '(None)',
                    raceseriesid: -1
                });
            }
        });
        config.store = typesStore;
        return config;
    },

    onEventTypesCmbSelect: function(combo, records, eOpts) {
        var me = this,
            val = combo.getValue();

        me.removeAll();
        me.processClubCalendar({
            filters: val == '-1' ? 'WHERE eventtypeid is null' : (val == '0' ? "" : 'WHERE eventtypeid = "' + val + '"')
        });

    },

    onSeriesCmbSelect: function(combo, records, eOpts) {
        var me = this,
            val = combo.getValue();

        me.removeAll();
        me.processClubCalendar({
            filters: val == '-1' ? 'WHERE raceseriesid is null' : (val == '0' ? "" : 'WHERE raceseriesid = "' + val + '"')
        });

    },

    onCalendar: function(eventStore) {
        this.calendarStore = Ext.create('Ext.calendar.data.MemoryCalendarStore', {
                    data: Ext.calendar.data.Calendars.getData()
                });

        this.add(
        {
                xtype: 'calendarpanel',
                eventStore: eventStore,
                calendarStore: this.calendarStore,
                border: false,
                itemId:'clubCalendar',
                id:'app-calendar',
                //region: 'center',
                activeItem: 3, // month view

                monthViewCfg: {
                    showHeader: true,
                    showWeekLinks: true,
                    showWeekNumbers: true
                },

                listeners: {
                    'eventclick': {
                        fn: function(vw, rec, el){
                            this.showEditWindow(rec, el);
                            this.clearMsg();
                        },
                        scope: this
                    },
                    'viewchange': {
                        fn: function(p, vw, dateInfo){
                            if(this.editWin){
                                this.editWin.hide();
                            }
                            if(dateInfo){
                                // will be null when switching to the event edit form so ignore
                                //Ext.getCmp('app-nav-picker').setValue(dateInfo.activeDate);
                                this.setTitle(dateInfo.viewStart, dateInfo.viewEnd);
                            }
                        },
                        scope: this
                    }

                }
            }

        );
    },

    showEditWindow: function(rec, animateTarget) {
        var me = this,
            recordRaw = rec.raw.recordRaw,
            raceConfig = GetEntityViewByName('race'),
            eventConfig = GetEntityViewByName('event');
        //debugger;

        var editForm = Ext.create('DynaMight.view.AddEdit', {
            entityConfig: recordRaw.raceid ? raceConfig : eventConfig,
            //entityStore: rec.raw.record.store,
            entityRecord: recordRaw

        });
        //debugger;
        editForm.form.setValues(recordRaw);
        var window = Ext.create('Ext.window.Window', {
            title: 'Edit' ,
            layout: 'vbox',
            modal: true,
            items: [
                editForm
            ],
            listeners: {
                close: function(){
                    me.removeAll();
                    me.processClubCalendar({});
                }
            }
        });
        editForm.parentWindow = window;
        window.show();


    },

    clearMsg: function() {
        //Ext.fly('app-msg').update('').addCls('x-hidden');
    },

    processRaceData: function(data) {
        var ret = [],
            d, today = Ext.Date.clearTime(new Date()),
            startDate,
            makeDate = function(date, d, h, m) {
                h = (h || 0) * 60;
                m = (m || 0);
                date = Ext.Date.add(date, Ext.Date.DAY, d);
                return Ext.Date.add(date, Ext.Date.MINUTE, h + m);
            };
        //debugger;
        for (d = 0; d < data.items.length; d++) {

            item = data.items[d];
            startDate = Ext.Date.clearTime(new Date(item.get('startdate')));
            ret.push(
            {
                "id": d,
                "cid": 2,
                "title": item.get('name'),
                "start": makeDate(startDate, 0, 1, 0),//Ext.Date.add(startDate, Ext.Date.SECOND, 1000),
                "end":  makeDate(startDate, 1, 0 , -1),//Ext.Date.add(startDate, Ext.Date.SECOND, 2000),
                "notes": item.get('name'),
                ad: true,
                recordRaw: item.raw,
                rem: item.raw.color,
                etid: item.raw.eventtypeid
            });


        }
        return ret;
    }

});