/*
 * File: app/view/EntityGrid.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMight.view.EntityGrid', {
    extend: 'Ext.grid.Panel',

    requires: [
        'Ext.grid.column.Column',
        'Ext.grid.View'
    ],

    height: 250,
    itemId: 'entityGridId',
    width: 400,
    title: 'My Grid Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'String'
                }
            ],
            viewConfig: {
                itemId: 'entityViewId'
            }
        });

        me.processEntityGrid(me);
        me.callParent(arguments);
    },

    processEntityGrid: function(config) {
        //custom config
        this.customConfig = {
            searchingFields: 'All',
            template: WORKFORCE_TEMPLATE
        };

        //this.store = new Ext.data.Store();
    }

});