/*
 * File: app/view/MainCt.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMightMobile.view.MainCt', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Panel',
        'Ext.TitleBar',
        'Ext.Img',
        'Ext.Label',
        'Ext.Button'
    ],

    config: {
        itemId: 'mainCtId',
        layout: 'fit',
        items: [
            {
                xtype: 'panel',
                cls: 'slide',
                itemId: 'homePanel',
                width: '100%',
                layout: 'fit'
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                height: 55,
                itemId: 'TitleBar',
                items: [
                    {
                        align: 'left',
                        itemId: 'navBtn',
                        iconCls: 'list',
                        ui: 'plain'
                    },
                    {
                        xtype: 'searchfield',
                        itemId: 'search',
                        //label: 'Query',
                        name: 'query',
                        width: 200,
                        hidden: true
                    },
                    {
                        align: 'right',
                        itemId: 'addBtn',
                        iconCls: 'add',
                        ui: 'plain',
                        hidden: true
                    }
                ],
                layout: {
                    type: 'hbox',
                    align: 'start'
                },
                items: [
                    {
                        xtype: 'container',
                        itemId: 'topCt1',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'image',
                                width: 70,
                                src: 'http://bystorm.com.au/DM/common/cyc_logo.png'
                            },
                            {
                                xtype: 'label',
                                cls: 'wizardTitle',
                                hidden: false,
                                html: 'Canberra Yacht Club',
                                itemId: 'topCardLbl'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        docked: 'left',
                        height: 50,
                        itemId: 'navBtn',
                        ui: 'plain',
                        width: 60,
                        iconCls: 'list'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        hidden: true,
                        itemId: 'syncLocalStorage',
                        ui: 'plain',
                        iconAlign: 'top',
                        iconCls: 'action'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        hidden: true,
                        itemId: 'loadLocalStorage',
                        ui: 'plain',
                        iconCls: 'download'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        itemId: 'mainLogInBtn',
                        ui: 'plain',
                        iconCls: 'user'
                    }
                ]
            }
        ]
    }

});