/*
 * File: app/view/RaceStartWizard.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMightMobile.view.RaceStartWizard', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Button',
        'Ext.Label',
        'Ext.field.Spinner',
        'Ext.field.Select',
        'Ext.ux.field.TimePicker',
        'Ext.ux.picker.Time'
    ],

    config: {
        itemId: 'seriesWizardId',
        scrollable: false,
        layout: {
            type: 'card',
            animation: 'slide'
        },
        items: [
            {
                xtype: 'formpanel',
                itemId: 'todayRaces',
                layout: 'vbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'container',
                        flex: 1,
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                margin: 5,
                                layout: 'fit',
                                title: 'Today\'s Races',
                                items: [
                                    {
                                        xtype: 'list',
                                        itemId: 'startRacesList',
                                        itemTpl: Ext.create('Ext.XTemplate', 
                                            '',
                                            '<div class="item">',
                                            '    <div class="name">{name}',
                                            '    </div>',
                                            '    <div class="vicinity">Start time: {[this.DateFormat(values.starttime)]}',
                                            '    </div>',
                                            '    ',
                                            '</div>',
                                            {
                                                DateFormat: function(date) {
                                                    //debugger;
                                                    return date ? Ext.Date.format(new Date(date), 'Y-m-d H:i') : '';
                                                }
                                            }
                                        )
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                margin: 5,
                                layout: 'fit',
                                title: 'Race Entrants',
                                items: [
                                    {
                                        xtype: 'dataview',
                                        itemId: 'entrantsList',
                                        inline: true,
                                        itemTpl: Ext.create('Ext.XTemplate', 
                                            '{[GetTemplate(\'boat\', values)]}',
                                            {
                                                getSignOn: function(date) {
                                                    return date ? "background-color:gold" : "";
                                                },
                                                DateFormat: function(date) {
                                                    //debugger;
                                                    return Ext.Date.format(date, 'Y-m-d H:i:s');
                                                }
                                            }
                                        )
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 40,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                disabled: true,
                                docked: 'right',
                                itemId: 'nextStartRacesBtn',
                                ui: 'decline-round',
                                text: 'Next >>'
                            },
                            {
                                xtype: 'label',
                                docked: 'right',
                                html: 'Select the race you want to start',
                                margin: 10,
                                style: 'color:darkblue'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'divisionDetails',
                layout: 'vbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'container',
                        flex: 1,
                        itemId: 'startId',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                itemId: 'startOrderCt',
                                margin: 5,
                                layout: 'vbox',
                                scrollable: 'both',
                                title: 'Start Order'
                            },
                            {
                                xtype: 'fieldset',
                                flex: 0.25,
                                itemId: 'divisionEntrantsId',
                                margin: 5,
                                layout: 'fit',
                                title: 'Division Entrants',
                                items: [
                                    {
                                        xtype: 'list',
                                        itemId: 'divisionEntrantsList',
                                        itemTpl: Ext.create('Ext.XTemplate', 
                                            '{[GetTemplate(\'boat\', values)]}',
                                            {
                                                getSignOn: function(date) {
                                                    return date ? "background-color:gold" : "";
                                                }
                                            }
                                        )
                                    },
                                    {
                                        xtype: 'button',
                                        docked: 'bottom',
                                        itemId: 'refreshStartOrderBtn',
                                        ui: 'action-round',
                                        text: 'Refresh'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 40,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'nextStartOrderBtn',
                                ui: 'decline-round',
                                text: 'Next'
                            },
                            {
                                xtype: 'label',
                                docked: 'right',
                                html: 'Configure the Start Sequence',
                                margin: 10,
                                style: 'color:darkblue'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'startDetails',
                layout: 'vbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'container',
                        flex: 1,
                        itemId: 'startId',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'fieldset',
                                flex: 0.3,
                                margin: 5,
                                width: 175,
                                layout: 'vbox',
                                title: 'Auto start',
                                items: [
                                    {
                                        xtype: 'spinnerfield',
                                        itemId: 'sequenceId',
                                        margin: 5,
                                        label: 'Sequence length',
                                        labelAlign: 'top',
                                        minValue: 1,
                                        stepValue: 1,
                                        defaultValue: 3
                                    },
                                    {
                                        xtype: 'spinnerfield',
                                        itemId: 'gapId',
                                        margin: 5,
                                        label: 'Starting Gap',
                                        labelAlign: 'top',
                                        minValue: 0,
                                        stepValue: 1
                                    },
                                    {
                                        xtype: 'button',
                                        itemId: 'startStopBtn',
                                        margin: 10,
                                        ui: 'confirm-round',
                                        text: 'Start/Stop'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                itemId: 'startOrderCt1',
                                margin: 5,
                                scrollable: true,
                                title: 'Start Order'
                            },
                            {
                                xtype: 'fieldset',
                                margin: 5,
                                width: 257,
                                layout: 'vbox',
                                title: 'Starters',
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        itemId: 'startDivisionCmb',
                                        margin: 10,
                                        maxWidth: 500,
                                        labelWidth: '50%',
                                        displayField: 'name',
                                        valueField: 'divisionid'
                                    },
                                    {
                                        xtype: 'list',
                                        flex: 1,
                                        itemId: 'startEntrantsList',
                                        itemTpl: Ext.create('Ext.XTemplate', 
                                            '{[GetTemplate(\'boat\', values)]}',
                                            {
                                                getSignOn: function(date) {
                                                    return date ? "background-color:gold" : "";
                                                }
                                            }
                                        )
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        margin: 5,
                        title: 'Flag display',
                        layout: {
                            type: 'hbox',
                            align: 'start'
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                                itemId: 'generalInfoAuxFS',
                                width: 468,
                                items: [
                                    {
                                        xtype: 'textfield',
                                        itemId: 'timerTxt',
                                        label: 'Sequence timer',
                                        name: 'timer',
                                        readOnly: true
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                itemId: 'ownerInfoFS',
                                width: 498
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 40,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                disabled: false,
                                docked: 'right',
                                itemId: 'nextStartPanelBtn',
                                ui: 'decline-round',
                                text: 'Review'
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                itemId: 'startBackBtn',
                                ui: 'decline-round',
                                text: 'Back'
                            },
                            {
                                xtype: 'label',
                                docked: 'right',
                                html: 'Start the Divisions',
                                margin: 10,
                                style: 'color:darkblue'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'formpanel',
                itemId: 'reviewCard',
                layout: 'vbox',
                scrollable: false,
                items: [
                    {
                        xtype: 'container',
                        flex: 1,
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'fieldset',
                                flex: 0.5,
                                layout: 'vbox',
                                title: 'Start Information',
                                items: [
                                    {
                                        xtype: 'list',
                                        flex: 1,
                                        itemId: 'raceDivisionsReviewList',
                                        itemTpl: Ext.create('Ext.XTemplate', 
                                            '',
                                            '<div class="item">',
                                            '    <div class="name">{dname}',
                                            '    </div>',
                                            '    <div class="vicinity">Start time: {[values.starttime]}',
                                            '    </div>',
                                            '    ',
                                            '</div>',
                                            {
                                                DateFormat: function(date) {
                                                    //debugger;
                                                    return Ext.Date.format(date, 'Y-m-d H:i:s');
                                                }
                                            }
                                        )
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                layout: 'fit',
                                title: 'Race Starters',
                                items: [
                                    {
                                        xtype: 'dataview',
                                        itemId: 'raceBoatsList',
                                        disableSelection: true,
                                        inline: true,
                                        itemTpl: [
                                            '{[GetTemplate(\'boat\', values)]}'
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        itemId: 'editDivisionButtonsCt',
                        margin: 10,
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'container',
                                itemId: 'editDivisionCt',
                                layout: {
                                    type: 'hbox',
                                    align: 'start'
                                }
                            },
                            {
                                xtype: 'button',
                                disabled: true,
                                itemId: 'startReviewApplyBtn',
                                margin: '0 20 0 20',
                                ui: 'action-round',
                                text: 'Apply'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        docked: 'bottom',
                        height: 40,
                        itemId: 'bottomCt',
                        margin: 10,
                        items: [
                            {
                                xtype: 'button',
                                docked: 'right',
                                itemId: 'exitStartRaceBtn',
                                ui: 'confirm-round',
                                text: 'Save Data'
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                itemId: 'startReviewBackBtn',
                                ui: 'decline-round',
                                text: 'Back'
                            }
                        ]
                    }
                ]
            }
        ]
    },

    initialize: function() {
        var me = this,
            boatStore = CreateStore("raceboat"),

            raceEntity = GetEntityByName("race"),
            raceStore = CreateStore("race"),
            boatDivisionsStore = CreateStore("raceboatdivision"),
            dStore = CreateStore("division");

        this.callParent();

        APP.WarningUnsavedData = false;

        boatStore.execConfig({
            params: {
                entityViewID: GetEntityViewByName('BR').entityviewid ,
                filters: 'WHERE cast(startdate as date) = curdate() order by signondate desc, hullnumber'
            }
        });

        //boatStore.filter('raceid', '0');

        raceStore.execConfig({
            params: {
                entityViewID: GetEntityView(raceEntity.entityid).entityviewid ,
                filters: 'WHERE cast(startdate as date) = curdate()'
            }
        });


        boatDivisionsStore.execConfig({
            params: {
                entityViewID: GetEntityViewByName('SD').entityviewid ,
                filters: ''
            }
        });

        dStore.execConfig({
            params: {
                entityViewID: GetEntityViewByName('AllDivisions').entityviewid ,
                filters: ''
            }
        });


        //debugger;
        me.boatStore = boatStore;
        me.seriesDivisionsStore = boatDivisionsStore;

        me.down('#startRacesList').setStore(raceStore);

        me.down('#divisionEntrantsList').setStore(boatStore);
        me.down('#entrantsList').setStore(boatStore);
        me.down('#startEntrantsList').setStore(boatStore);
        me.down('#raceBoatsList').setStore(boatStore);


        me.down('#raceDivisionsReviewList').setStore(boatDivisionsStore);

        me.down('#startDivisionCmb').setStore(dStore);

        me.down('#editDivisionCt').add({
            xtype: 'timepickerfield',
            itemId: 'divisionTime',
            name: 'defaultTime',
            label: 'Time',
            dateFormat: 'H:i:s',
            picker:{
                slotOrder: ['hour','minute','second'],
                endHour: 23
            },
            listeners: {
                //hide: me.onDivisionTimeChange
            }
        });

        Ext.Viewport.setMasked(false);
    },

    onDivisionTimeChange: function() {

    }

});