/*
 * File: app/view/RaceDuty.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMightMobile.view.RaceDuty', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.Search',
        'Ext.dataview.DataView',
        'Ext.XTemplate',
        'Ext.field.Select'
    ],

    config: {
        itemId: 'raceDutyFrm',
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                itemId: 'raceCrewDutyToolbar',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'setRaceDutyBtn',
                        ui: 'confirm',
                        width: 150,
                        text: 'Set duty'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                flex: 1,
                itemId: 'raceDutyFs',
                margin: 5,
                title: 'Races',
                layout: {
                    type: 'vbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        itemId: 'raceDutySearchTxt'
                    },
                    {
                        xtype: 'dataview',
                        flex: 1,
                        height: '100%',
                        itemId: 'raceDutyLst',
                        mode: 'MULTI',
                        inline: true,
                        itemTpl: [
                            '<div class="item">',
                            '    <div class="name">{name}</div>',
                            '</div>',
                            ''
                        ]
                    }
                ]
            },
            {
                xtype: 'fieldset',
                flex: 1,
                itemId: 'crewMemberDutyFS',
                margin: 5,
                title: 'Crew',
                layout: {
                    type: 'vbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        itemId: 'crewMemberSearch'
                    },
                    {
                        xtype: 'dataview',
                        flex: 1,
                        itemId: 'crewMembersLst',
                        mode: 'MULTI',
                        inline: true,
                        itemTpl: [
                            '',
                            '<div class="item">',
                            '    <div class="name">{firstname} {surname}',
                            '    </div>',
                            '    <div class="vicinity">{ya}',
                            '    </div>',
                            '    ',
                            '</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'selectfield',
                itemId: 'dutyTypeSelectField',
                label: 'Duty',
                displayField: 'name',
                valueField: 'dutytypeid'
            }
        ]
    },

    initialize: function() {
        var me = this,
            dutyTypes = CreateStore("dutytype");

        this.callParent();

        dutyTypes.execConfig({
            params: {
                entityViewID: GetEntityViewByName('DutyTypes').entityviewid ,
                filters: ''
            }
        });

        me.down('#dutyTypeSelectField').setStore(dutyTypes);

        Ext.Viewport.setMasked(false);
    }

});