/*
 * File: app/view/SkipperInformation.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DynaMightMobile.view.SkipperInformation', {
    extend: 'Ext.form.Panel',
    alias: 'widget.skiperInforamtion',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Hidden',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Toolbar',
        'Ext.Spacer'
    ],

    config: {
        itemId: 'skipperInfoForm',
        margin: 5,
        layout: {
            type: 'hbox',
            pack: 'center'
        },
        items: [
            {
                xtype: 'fieldset',
                flex: 1,
                itemId: 'ownerInfoFS',
                width: 498,
                title: 'Skipper Information',
                items: [
                    {
                        xtype: 'textfield',
                        hidden: true,
                        itemId: 'crewMemberId',
                        name: 'crewmemberid'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'skiperYATxt',
                        label: 'Skipper ID',
                        name: 'ya',
                        required: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Name',
                        name: 'firstname',
                        required: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Surname',
                        name: 'surname'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Email',
                        name: 'email',
                        required: true
                    },
                    {
                        xtype: 'textfield',
                        label: 'Mobile',
                        name: 'mobilenumber',
                        required: true
                    },
                    {
                        xtype: 'hiddenfield',
                        name: 'raceseriesboatid'
                    },
                    {
                        xtype: 'button',
                        itemId: 'clearSkiperFSData',
                        margin: '5 0 0 0',
                        ui: 'action',
                        text: 'Clear'
                    }
                ]
            },
            {
                xtype: 'list',
                flex: 1,
                itemId: 'skipperList',
                itemTpl: [
                    '<div class="item">',
                    '    <div class="name">YA -{name}</div>',
                    '    <div class="name">Name - {firstname} {surname}</div>',
                    '</div>'
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                itemId: 'skipperInformationToolbar',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'saveSkipperInformation',
                        ui: 'confirm',
                        text: 'Save'
                    }
                ]
            }
        ]
    }

});